import numpy


trans = {
    "room1": {
        "room1": 0,
        "room2": 0.45,
        "room3": 0.45,
        "room4": 0,
        "room5": 0,
        "room6": 0,
        "room7": 0,
        "room8": 0,
        "room9": 0,
        "trap": 0.1,
    },
    "room2": {
        "room1": 1,
        "room2": 0,
        "room3": 0,
        "room4": 0,
        "room5": 0,
        "room6": 0,
        "room7": 0,
        "room8": 0,
        "room9": 0,
        "trap": 0,
    },
    "room3": {
        "room1": 0.25,
        "room2": 0,
        "room3": 0,
        "room4": 0.25,
        "room5": 0.25,
        "room6": 0.25,
        "room7": 0,
        "room8": 0,
        "room9": 0,
        "trap": 0,
    },
    "room4": {
        "room1": 0,
        "room2": 0,
        "room3": 1,
        "room4": 0,
        "room5": 0,
        "room6": 0,
        "room7": 0,
        "room8": 0,
        "room9": 0,
        "trap": 0,
    },
    "room5": {
        "room1": 0,
        "room2": 0,
        "room3": 1,
        "room4": 0,
        "room5": 0,
        "room6": 0,
        "room7": 0,
        "room8": 0,
        "room9": 0,
        "trap": 0,
    },
    "room6": {
        "room1": 0,
        "room2": 0,
        "room3": 0.5,
        "room4": 0,
        "room5": 0,
        "room6": 0,
        "room7": 0.5,
        "room8": 0,
        "room9": 0,
        "trap": 0,
    },
    "room7": {
        "room1": 0,
        "room2": 0,
        "room3": 0,
        "room4": 0,
        "room5": 0,
        "room6": 0.33,
        "room7": 0,
        "room8": 0.33,
        "room9": 0.33,
        "trap": 0,
    },
    "room8": {
        "room1": 0,
        "room2": 0,
        "room3": 0,
        "room4": 0,
        "room5": 0,
        "room6": 0,
        "room7": 1,
        "room8": 0,
        "room9": 0,
        "trap": 0,
    },
    "room9": {
        "room1": 0,
        "room2": 0,
        "room3": 0,
        "room4": 0,
        "room5": 0,
        "room6": 0,
        "room7": 1,
        "room8": 0,
        "room9": 0,
        "trap": 0,
    },
    "trap": {
        "room1": 0,
        "room2": 0,
        "room3": 0,
        "room4": 0,
        "room5": 0,
        "room6": 0,
        "room7": 0,
        "room8": 0,
        "room9": 0,
        "trap": 0,
    },
}